### ISSUE TITLE
Client Reach Out

### ISSUE THREAD

**Issue by piratechs19** [Piratechs-LLC/Piratechs#70]
- [x] Make sure Rust can see designs on Contract
- [x] Reach out to Brandy about Project Escape Needs
- [x] Talk to Edgar about PVE: E-Sports Company
- [x] Reach back out to Marietta Salon
- [x] News App & Animations Guy
