### ISSUE TITLE
$💲Piratechs Hours

### ISSUE THREAD

**Issue by strawhat19** [Piratechs-LLC/Piratechs#73]
- [ ] Chandler
     - [ ] Adv:💲35 x 🕝 0 ✅ 9/17/2022
     - [ ] Work:💲25 x 🕝 0 ✅ 9/17/2022
- [ ] Makayla
    - [ ] Adv:💲35 x 🕝 0 ✅ 9/17/2022
    - [ ] Work:💲25 x 🕝 0 ✅ 9/17/2022

**Comment by strawhat19** [comment]
> * [x]  Chandler: 💲35 x 🕝8 = 💲280.00 ✅ 8/3/2022
> * [x]  Makayla: 💲35 x 🕝3 = 💲75.00 ✅ 8/3/2022

**Comment by kaymiika** [comment]
Note for Ricky because I think chan and I are still confused:

I just updated the MAIN post here and changed my hours for this pay period to **2** and the total money to **$70**
Let me know if I did this incorrectly or anything c:

Chandler also thought the math on his number is wrong? As in 3 x 35 = 105 not 75, but if you have a particular reason for that just let us know, we might just be confused hahaha

**Comment by Xuruko** [comment]
> * [ ]  Chandler: 💲35 x 🕝8 = 8/11/2022
     - 3 hours from last pay period that we had missed. 2 hours this week on the Experience Page edits. 3 hours on the Party Room additions
> * [ ]  Makayla: 💲35 x 🕝2 = 💲70.00 ✅ 8/11/2022

**Comment by strawhat19** [comment]
> * [x]  Chandler: 💲35 x 🕝 9 = 💲315.00 ✅ 8/11/2022
> * [x]  Makayla: 💲35 x 🕝 3 = 💲105.00 ✅ 8/11/2022

**Comment by Xuruko** [comment]
> * [ ]  Chandler: 💲25 - 💲35 x 🕝 2 = 💲0.00 ✅ 8/25/2022
- 2 hours on Disabling Contact Forms and Replacing with new section.
> * [ ]  Makayla: 💲25 - 💲35 x 🕝 0 = 💲0.00 ✅ 8/25/2022

**Comment by strawhat19** [comment]
> * [x]  Chandler: 💲25 - 💲35 x 🕝 7 = 💲235.00 ✅ 8/25/2022
> * [x]  Makayla: 💲25 - 💲35 x 🕝 0 = 💲0.00 ✅ 8/25/2022
> * [x]  Chandler & Makayla Elaphaea Commission: 💲350.00 ✅ 8/25/2022

**Comment by strawhat19** [comment]
-Makayla notes 8/28: Meeting 1.5hrs = ($37.50), Project escape style mockups 1.5hrs = (?), Elaphea mockups 2hrs = (?)

**Comment by strawhat19** [comment]
> * [x]  Chandler: 💲35 x 🕝 1.5 = 💲52.50 ✅ 9/1/2022
> * [x]  Makayla: 💲35 x 🕝 5 = 💲175 ✅ 9/1/2022

**Comment by Xuruko** [comment]
- [ ] Chandler 1 hour meeting
- [ ] Makayla 1 hour meeting

**Comment by strawhat19** [comment]
> * [x]  Chandler
>   
>   * [x]  Adv:💲35 x 🕝 4 = 💲140.00 ✅ 9/10/2022
>   * [x]  Work:💲25 x 🕝 3.5 = 💲87.50 ✅ 9/10/2022
> * [x]  Makayla
>   
>   * [x]  Adv:💲35 x 🕝 2 = 💲70.00 ✅ 9/10/2022
>   * [x]  Work:💲25 x 🕝 6.5 = 💲162.50 ✅ 9/10/2022

**Comment by kaymiika** [comment]
- [ ] Makayla - 9/10 - Clocked 2 hrs editing Elaphaea login.css to change the appearance of login form
          - Added Lato font
          - Added Shadows and inset, filter brightness when hovering buttons
          - added border to deviantart button
          - Started to change the user/pass form, got a bit stuck but one of them is gray now lol

**Comment by Xuruko** [comment]
[ ] Chandler - 9/12 
     - 4 hours total
          - 3 hours on organizing code, editing Username and Pass boxes, attempting to get the checkmark to properly display
          - 1 hour on research, couple YouTube videos and some blog posts

**Comment by strawhat19** [comment]
> * [x]  Chandler
>   
>   * [x]  Adv:💲35 x 🕝 2 = 💲70.00 ✅ 9/16/2022
>   * [x]  Work:💲25 x 🕝 3.5 = 💲87.50 ✅ 9/16/2022
>   * [x]  Total Paid: 💲160.00 ✅ 9/16/2022
> * [x]  Makayla
>   
>   * [x]  Adv:💲35 x 🕝 3.5 = 💲122.50 ✅ 9/16/2022
>   * [x]  Work:💲25 x 🕝 1.5 = 💲37.50 ✅ 9/16/2022
>   * [x]  Total Paid: 💲160.00 ✅ 9/16/2022

**Comment by Xuruko** [comment]
-[ ] Chandler - 9/16
     - 2 hours total
     - Research on Wordpress CSS editing. Trial and error editing Sign-In page. Not really any progress unfortunately but I'm tryin

**Comment by Xuruko** [comment]
- [ ] Chandler - 9/19
     - 2 hours total
     - More research and trial and error. Edited the Login page to fix the Login button not being blue and the hover state. Fixed DeviantArt button to not have a seizure when hovered. Need to actually edit the Clicked state though.

**Comment by Xuruko** [comment]
- [ ] Chandler - 9/20
     - 2 hours total
     - Straight research on Wordpress CSS

**Comment by strawhat19** [comment]
> * [x]  Chandler
>   
>   * [x]  💲35 x 🕝 2 =💲70.00 ✅ 9/23/2022
>   * [x]  💲25 x 🕝 4 =💲100.00 ✅ 9/23/2022
> * [ ]  Makayla
>   
>   * [ ]  💲35 x 🕝 0 ✅ 9/23/2022
>   * [ ]  💲25 x 🕝 0 ✅ 9/23/2022

**Comment by kaymiika** [comment]
- [ ] Makayla - 9/25
         - 1 hour spent going through entire Elaphaea website, clicking all pages and links, and recording broken or empty pages

**Comment by Xuruko** [comment]
- [ ] Chandler - 9/26 - 2.5 hours
     - [ ] Going through every page of Elaphaea and making sure the new theme wasn't broken anywhere or glaring errors
     - [ ] Started a new Task and began writing down simple fixes and changes that needed to be made

**Comment by Xuruko** [comment]
- [ ] Chandler - 9/28 - 2 hours
     - [ ] Added border radius to forms and buttons on Dashboard. Changed hover state of buttons to still be visible. 
     - [ ] Added Border and Border Radius to character image itself

     - [ ] Attempted to edit the width of the form inputs to be responsive with the Gray Column they're on.
     - [ ] Attempted to edit the "Upload" box over the Character Design to be responsive with the Character Design box

**Comment by strawhat19** [comment]
> * [x]  Chandler
>   
>   * [x]  💲35 x 🕝 2.5 = 💲87.50 ✅ 9/29/2022
>   * [x]  💲25 x 🕝 8.5 = 💲212.50 ✅ 9/29/2022
>   * [x]  💲Total = 💲300.00 ✅ 9/29/2022
> * [x]  Makayla
>   
>   * [x]  💲35 x 🕝 3 =  💲105.00 ✅ 9/29/2022
>   * [x]  💲25 x 🕝 9.5 = 💲237.50 ✅ 9/29/2022
>   * [x]  💲Total = 💲342.50 ✅ 9/29/2022
